### PR TITLE
Switch macOS from `firefox-bin` to `firefox`

### LINKED ISSUE #328: Cannot start Firefox (or FirefoxHeadless) 121 on macOS Sonoma 14.2.1 (23C71)
I cannot start Firefox (or FirefoxHeadless) 121 on macOS Sonoma `14.2.1 (23C71)`. It used to work on that very OS a few weeks ago, possibly with Firefox 120. EDIT: confirmed - this issue will affect everyone on recent macOS running Firefox 121 or newer.

A very simple test case doesn't work, just follow instructions from https://github.com/mgol/karma-test. When doing so, I am getting:
```
$ npm test 

> test
> karma start

09 01 2024 00:04:55.436:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
09 01 2024 00:04:55.437:INFO [launcher]: Launching browsers ChromeHeadless, FirefoxHeadless with concurrency unlimited
09 01 2024 00:04:55.439:INFO [launcher]: Starting browser ChromeHeadless
09 01 2024 00:04:55.441:INFO [launcher]: Starting browser FirefoxHeadless
09 01 2024 00:04:55.446:ERROR [launcher]: Cannot start FirefoxHeadless
	
09 01 2024 00:04:55.446:ERROR [launcher]: FirefoxHeadless stdout: 
09 01 2024 00:04:55.446:ERROR [launcher]: FirefoxHeadless stderr: 
09 01 2024 00:04:55.447:INFO [launcher]: Trying to start FirefoxHeadless again (1/2).
09 01 2024 00:04:55.451:ERROR [launcher]: Cannot start FirefoxHeadless
	
09 01 2024 00:04:55.451:ERROR [launcher]: FirefoxHeadless stdout: 
09 01 2024 00:04:55.451:ERROR [launcher]: FirefoxHeadless stderr: 
09 01 2024 00:04:55.451:INFO [launcher]: Trying to start FirefoxHeadless again (2/2).
09 01 2024 00:04:55.455:ERROR [launcher]: Cannot start FirefoxHeadless
	
09 01 2024 00:04:55.455:ERROR [launcher]: FirefoxHeadless stdout: 
09 01 2024 00:04:55.455:ERROR [launcher]: FirefoxHeadless stderr: 
09 01 2024 00:04:55.455:ERROR [launcher]: FirefoxHeadless failed 2 times (cannot start). Giving up.
09 01 2024 00:04:55.606:INFO [Chrome Headless 120.0.6099.199 (Mac OS 10.15.7)]: Connected on socket kepyKrJsYaeTHzTRAAAB with id 45000797
Chrome Headless 120.0.6099.199 (Mac OS 10.15.7): Executed 1 of 1 SUCCESS (0.001 secs / 0 secs)
TOTAL: 1 SUCCESS
```

The error message is the same as in #93. However, I am running it directly on a normal OS, not behind Docker.

### PR DESCRIPTION
**Pull request by Krinkle**
Upstream:
* "firefox-bin is broken". https://bugzilla.mozilla.org/show_bug.cgi?id=1871447
* "remove firefox-bin". https://bugzilla.mozilla.org/show_bug.cgi?id=1873782

Long story short:
* Firefox has shipped both for a long time.
* Firefox signs the binaries in a way that  only `firefox` passes Apple's "hightened" security rules.
* Firefox 121 adds support for Apple's Passkey feature and that raised the level of security rules it has to pass, thus making `firefox-bin` appear like an imposter. This means macOS terminates `firefox-bin` with the message `Killed: 9`. 

Fixes https://github.com/karma-runner/karma-firefox-launcher/issues/328.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -171,7 +171,7 @@ const getFirefoxWithFallbackOnOSX = function () {
 
   const firefoxDirNames = Array.prototype.slice.call(arguments)
   const prefix = '/Applications/'
-  const suffix = '.app/Contents/MacOS/firefox-bin'
+  const suffix = '.app/Contents/MacOS/firefox'
```
Comment (whimboo) [inline index.js:174]: For even a better stability over time and to have code that is not tight to a specific browser executalbe it would be probably better to read out the `Info.plist` file for the executable bundle. We now do that in geckodriver as well.

Comment (Krinkle) [reply index.js:174]: Ack, perhaps in a later change. Doing that synchronously, and without new dependencies, and such that we can still cleanly decide between multiple optional applications, will be non-trivial. Also considering that Karma is deprecated and in maintenance mode basically, it will be hard to get a maintainer to review and land this swiftly as-is.

**Review by mgol — APPROVED** [review]
I confirm this fixes the issue I reported in #328

**Comment by mgol** [comment]
Given the following deprecation notice:
https://github.com/karma-runner/karma-firefox-launcher/blob/a55a7f43fd8ecdce02fb9a558ed769381add8083/README.md#karma-firefox-launcher-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes
I am not sure if we'll get this fix merged. 😕 From the linked note:
> Critical security issues in Karma will still be triaged and fixed as necessary.

**Review by pmvald — APPROVED** [review]

**Comment by Krinkle** [comment]
@pmvald Thanks for merging this PR! Could you release this as well? Or are there other changes or steps we need to follow first? Let me know if I can help with anything.

**Comment by pmvald** [comment]
The release is automatic. This PR did not follow PR naming [guidelines](https://karma-runner.github.io/latest/dev/git-commit-msg.html) and so it did not trigger release for a new version by semver. I'll merge a bunch of other PRs which hopefully trigger a release.
